/* Desafios — boss fight de cada trilha. Só dados (ADR-007).

   Cada desafio testa o conteúdo inteiro da trilha em cenários de jogo
   contra o Dom Naipe. O id é estável: `desafio-{trilhaId}`.

   Cenários novos entram no fim; a posição na lista não significa nada
   pro progresso (gravado pelo id do desafio, não do cenário). */

import type { Desafio } from "@/lib/dominio/tipos.ts";

export const DESAFIOS: Desafio[] = [
  {
    id: "desafio-f",
    trilhaId: "f",
    nome: "Desafio dos Fundamentos",
    cenarios: [
      {
        situacao: "Primeira mão da noite. Você recebe suas cartas.",
        mao: ["K♠", "K♥"],
        pergunta: "O que você tem na mão?",
        opcoes: ["Carta alta", "Um par de reis", "Dois pares", "Full house"],
        correta: 1,
        explicacao: "Duas cartas do mesmo valor = par. Par de reis é mão inicial fortíssima.",
        acerto: "perde",
        erro: "ri",
      },
      {
        situacao: "O flop abre. Dom Naipe olha pro board com cara de quem acertou alguma coisa.",
        mao: ["A♥", "J♥"],
        board: ["Q♥", "8♥", "3♦"],
        pergunta: "Quantas cartas do mesmo naipe você tem?",
        opcoes: ["2", "3", "4", "5"],
        correta: 2,
        explicacao: "A♥, J♥ da sua mão + Q♥, 8♥ do board = 4 copas. Falta uma pro flush.",
        acerto: "pensa",
        erro: "provoca",
      },
      {
        situacao: "River caiu. Hora do showdown.",
        mao: ["10♠", "J♠"],
        board: ["Q♣", "K♦", "A♥", "3♠", "7♦"],
        pergunta: "Que mão você formou?",
        opcoes: ["Carta alta", "Um par", "Sequência", "Flush"],
        correta: 2,
        explicacao: "10-J-Q-K-A em ordem = sequência (straight). Não precisa ser do mesmo naipe.",
        acerto: "perde",
        erro: "ri",
      },
      {
        situacao: "Dom Naipe faz uma aposta grande. Você olha suas cartas.",
        mao: ["7♠", "2♦"],
        pergunta: "Alguém apostou forte. O que você faz?",
        opcoes: ["Call — pagar pra ver", "Raise — aumentar o pote", "Fold — desistir", "All-in"],
        correta: 2,
        explicacao: "7-2 offsuit é a pior mão do jogo. Fold. Ficha guardada é ficha ganha.",
        acerto: "pensa",
        erro: "provoca",
      },
      {
        situacao: "Mesa final. Você e Dom Naipe mostram as cartas.",
        mao: ["A♦", "K♣"],
        board: ["K♠", "9♥", "4♣", "2♦", "7♠"],
        maoDom: ["9♠", "9♦"],
        pergunta: "Quem ganha esse showdown?",
        opcoes: ["Você — par de reis", "Dom Naipe — trinca de noves", "Empate", "Ninguém, o board decide"],
        correta: 1,
        explicacao: "Dom Naipe tem 9♠ 9♦ + 9♥ do board = trinca de noves. Trinca ganha de par. Ele levou essa!",
        acerto: "perde",
        erro: "ri",
      },
      {
        situacao: "Você está no botão. Três jogadores já falaram antes.",
        mao: ["J♠", "10♠"],
        pergunta: "Por que essa posição é boa?",
        opcoes: [
          "Porque o botão dá cartas melhores",
          "Porque você age por último e já viu o que todos fizeram",
          "Porque você não precisa pagar blind",
          "Não é boa — posição não importa",
        ],
        correta: 1,
        explicacao: "No botão você age por último pós-flop. Informação máxima: decide sabendo o que os outros fizeram.",
        acerto: "perde",
        erro: "provoca",
      },
      {
        situacao: "Última mão. Dom Naipe está all-in. Showdown decisivo.",
        mao: ["8♣", "8♠"],
        board: ["8♥", "K♣", "K♠", "5♦", "2♥"],
        maoDom: ["K♦", "5♣"],
        pergunta: "Quem leva o pote?",
        opcoes: [
          "Você — full house de oitos",
          "Dom Naipe — full house de reis",
          "Empate — os dois têm full house",
          "Dom Naipe — dois pares",
        ],
        correta: 1,
        explicacao: "Dom Naipe: K♦ + K♣ K♠ (trinca de reis) + 5♣ 5♦ (par de cincos) = full house de reis. Reis full de cincos > oitos full de reis. Dom Naipe venceu!",
        acerto: "perde",
        erro: "ri",
      },
    ],
  },
  {
    id: "desafio-p",
    trilhaId: "p",
    nome: "Desafio do Pré-flop",
    cenarios: [
      {
        situacao: "Início da sessão. Você está em early position.",
        mao: ["A♠", "A♥"],
        pergunta: "O que você faz com essa mão?",
        opcoes: ["Limp — pagar 1 BB", "Raise de 2,5-3 BB", "Fold", "All-in"],
        correta: 1,
        explicacao: "AA é a melhor mão do poker. Abra com raise — limp desperdiça o valor da mão.",
        acerto: "pensa",
        erro: "provoca",
      },
      {
        situacao: "Botão. Todos deram fold até você.",
        mao: ["K♠", "Q♠"],
        pergunta: "Essa mão é suited. Isso importa?",
        opcoes: [
          "Não, naipe não muda nada",
          "Sim, ganha chance de flush — vale um pouco mais",
          "Sim, o naipe desempata se alguém tiver a mesma mão",
          "Sim, suited ganha de qualquer par",
        ],
        correta: 1,
        explicacao: "Mesmo naipe soma a chance de flush. Não transforma lixo em ouro, mas mão boa fica um pouco melhor.",
        acerto: "perde",
        erro: "ri",
      },
      {
        situacao: "Meio da mesa. Dois jogadores já deram limp.",
        mao: ["J♦", "10♥"],
        pergunta: "Dois jogadores fizeram limp. Você tem J10 offsuit no meio. Melhor jogada?",
        opcoes: [
          "Limp junto — é barato",
          "Raise pra isolar e levar a iniciativa",
          "Fold — posição ruim pra mão marginal",
          "All-in — pressionar quem limpou",
        ],
        correta: 1,
        explicacao: "Raise isola quem limpou e coloca você no comando do pote. Limpar junto é entrar de mão fraca sem informação.",
        acerto: "pensa",
        erro: "provoca",
      },
      {
        situacao: "Big blind. Alguém abriu raise de 3 BB.",
        mao: ["7♣", "2♠"],
        pergunta: "Você está no big blind com 7-2 off. Alguém fez raise. O que fazer?",
        opcoes: ["Call — já paguei 1 BB, falta pouco", "Raise", "Fold", "All-in"],
        correta: 2,
        explicacao: "7-2 offsuit é a pior mão do jogo. O BB que já pagou é custo afundado — não é razão pra continuar.",
        acerto: "perde",
        erro: "ri",
      },
      {
        situacao: "Dom Naipe abriu raise do cutoff. Você está no botão.",
        mao: ["A♥", "Q♥"],
        pergunta: "Dom Naipe abriu 2,5 BB do cutoff. Você tem AQ suited no botão. Melhor ação?",
        opcoes: ["Fold", "Call", "3-bet (raise por cima)", "Limp"],
        correta: 2,
        explicacao: "AQ suited no botão contra abertura do cutoff é mão forte. 3-bet constrói pote com vantagem de posição. Call também é aceitável.",
        acerto: "perde",
        erro: "provoca",
      },
    ],
  },
] satisfies Desafio[];
